module.exports = {
    baseUrl: '/sdasdadsdas/',
    modes: {
        "APL":"apl",
        "PGP":"asciiarmor",
        "ASN.1":"asn.1",
        "Asterisk":"asterisk",
        "Brainfuck":"brainfuck",
        "C":"clike",
        "C++":"clike",
        "Cobol":"cobol",
        "C#":"clike",
        "Clojure":"clojure",
        "ClojureScript":"clojure",
        "Closure Stylesheets (GSS)":"css",
        "CMake":"cmake",
        "CoffeeScript":"coffeescript",
        "Common Lisp":"commonlisp",
        "Cypher":"cypher",
        "Cython":"python",
        "Crystal":"crystal",
        "CSS":"css",
        "CQL":"sql",
        "D":"d",
        "Dart":"dart",
        "diff":"diff",
        "Django":"django",
        "Dockerfile":"dockerfile",
        "DTD":"dtd",
        "Dylan":"dylan",
        "EBNF":"ebnf",
        "ECL":"ecl",
        "edn":"clojure",
        "Eiffel":"eiffel",
        "Elm":"elm",
        "Embedded Javascript":"htmlembedded",
        "Embedded Ruby":"htmlembedded",
        "Erlang":"erlang",
        "Factor":"factor",
        "FCL":"fcl",
        "Forth":"forth",
        "Fortran":"fortran",
        "F#":"mllike",
        "Gas":"gas",
        "Gherkin":"gherkin",
        "GitHub Flavored Markdown":"gfm",
        "Go":"go",
        "Groovy":"groovy",
        "HAML":"haml",
        "Haskell":"haskell",
        "Haskell (Literate)":"haskell-literate",
        "Haxe":"haxe",
        "HXML":"haxe",
        "ASP.NET":"htmlembedded",
        "HTML":"htmlmixed",
        "HTTP":"http",
        "IDL":"idl",
        "Pug":"pug",
        "Java":"clike",
        "Java Server Pages":"htmlembedded",
        "JavaScript":"javascript",
        "JSON":"javascript",
        "JSON-LD":"javascript",
        "JSX":"jsx",
        "Jinja2":"jinja2",
        "Julia":"julia",
        "Kotlin":"clike",
        "LESS":"css",
        "LiveScript":"livescript",
        "Lua":"lua",
        "Markdown":"markdown",
        "mIRC":"mirc",
        "MariaDB SQL":"sql",
        "Mathematica":"mathematica",
        "Modelica":"modelica",
        "MUMPS":"mumps",
        "MS SQL":"sql",
        "mbox":"mbox",
        "MySQL":"sql",
        "Nginx":"nginx",
        "NSIS":"nsis",
        "NTriples":"ntriples",
        "Objective C":"clike",
        "OCaml":"mllike",
        "Octave":"octave",
        "Oz":"oz",
        "Pascal":"pascal",
        "PEG.js":"pegjs",
        "Perl":"perl",
        "PHP":"php",
        "Pig":"pig",
        "Plain Text":"null",
        "PLSQL":"sql",
        "PowerShell":"powershell",
        "Properties files":"properties",
        "ProtoBuf":"protobuf",
        "Python":"python",
        "Puppet":"puppet",
        "Q":"q",
        "R":"r",
        "reStructuredText":"rst",
        "RPM Changes":"rpm",
        "RPM Spec":"rpm",
        "Ruby":"ruby",
        "Rust":"rust",
        "SAS":"sas",
        "Sass":"sass",
        "Scala":"clike",
        "Scheme":"scheme",
        "SCSS":"css",
        "Shell":"shell",
        "Sieve":"sieve",
        "Slim":"slim",
        "Smalltalk":"smalltalk",
        "Smarty":"smarty",
        "Solr":"solr",
        "Soy":"soy",
        "SPARQL":"sparql",
        "Spreadsheet":"spreadsheet",
        "SQL":"sql",
        "Squirrel":"clike",
        "Swift":"swift",
        "sTeX":"stex",
        "LaTeX":"stex",
        "SystemVerilog":"verilog",
        "Tcl":"tcl",
        "Textile":"textile",
        "TiddlyWiki":"tiddlywiki",
        "Tiki wiki":"tiki",
        "TOML":"toml",
        "Tornado":"tornado",
        "troff":"troff",
        "TTCN":"ttcn",
        "TTCN_CFG":"ttcn-cfg",
        "Turtle":"turtle",
        "TypeScript":"javascript",
        "Twig":"twig",
        "Web IDL":"webidl",
        "VB.NET":"vb",
        "VBScript":"vbscript",
        "Velocity":"velocity",
        "Verilog":"verilog",
        "VHDL":"vhdl",
        "XML":"xml",
        "XQuery":"xquery",
        "Yacas":"yacas",
        "YAML":"yaml",
        "Z80":"z80",
        "mscgen":"mscgen",
        "xu":"mscgen",
        "msgenny":"mscgen"
    },
    themes: {
        "default":"default",
         "3024-day":"3024-day",
         "3024-night":"3024-night",
         "abcdef":"abcdef",
         "ambiance":"ambiance",
         "base16-dark":"base16-dark",
         "base16-light":"base16-light",
         "bespin":"bespin",
         "blackboard":"blackboard",
         "cobalt":"cobalt",
         "colorforth":"colorforth",
         "dracula":"dracula",
         "eclipse":"eclipse",
         "elegant":"elegant",
         "erlang-dark":"erlang-dark",
         "hopscotch":"hopscotch",
         "icecoder":"icecoder",
         "isotope":"isotope",
         "lesser-dark":"lesser-dark",
         "liquibyte":"liquibyte",
         "material":"material",
         "mbo":"mbo",
         "mdn-like":"mdn-like",
         "midnight":"midnight",
         "monokai":"monokai",
         "neat":"neat",
         "neo":"neo",
         "night":"night",
         "panda-syntax":"panda-syntax",
         "paraiso-dark":"paraiso-dark",
         "paraiso-light":"paraiso-light",
         "pastel-on-dark":"pastel-on-dark",
         "railscasts":"railscasts",
         "rubyblue":"rubyblue",
         "seti":"seti",
         "solarized dark":"solarized dark",
         "solarized light":"solarized light",
         "the-matrix":"the-matrix",
         "tomorrow-night-bright":"tomorrow-night-bright",
         "tomorrow-night-eighties":"tomorrow-night-eighties",
         "ttcn":"ttcn",
         "twilight":"twilight",
         "vibrant-ink":"vibrant-ink",
         "xq-dark":"xq-dark",
         "xq-light":"xq-light",
         "yeti":"yeti",
         "zenburn":"zenburn"
    }
};